swipe:
    3:
        left:
        command: 'xdotool key Ctrl+Super+Left'
        right:
        command: 'xdotool key Ctrl+Super+Right'
        up:
        command: 'xdotool key super+m'
        down:
        command: 'xdotool key super+m'
    4:
        up:
        command: 'xdotool key Ctrl+Super+Up'
        down:
        command: 'xdotool key Ctrl+Super+Down'
        left:
        command: 'xdotool key alt+Shift+Tab'
        right:
        command: 'xdotool key alt+Tab'
        
pinch:
    in:
        command: 'xdotool key super+a'
        threshold: 0.1
    out:
        command: 'xdotool key super'
        threshold: 0.1

threshold:
    swipe: 1
    pinch: 1

interval:
    swipe: 1
    pinch: 1
