swipe:
    3:
        left:
            command: 'xdotool key alt+Left' # History right
        right:
            command: 'xdotool key alt+Right' # History forward
        up:
            command: 'xdotool key ctrl+t' # Open new tab
        down:
            command: 'xdotool key ctrl+w' # Close tab
    4:
        left:
            command: 'xdotool key Ctrl+Super+Left'
        right:
            command: 'xdotool key Ctrl+Super+Right' 
        up:
            command: 'xdotool key super+ctrl+down' # Workspace overview
        down:
            command: 'xdotool key super+ctrl+up' # Window overview

pinch:
    in:
        command: 'xdotool key super+a'
        threshold: 0.1
    out:
        command: 'xdotool key super'
        threshold: 0.1

threshold:
    swipe: 1
    pinch: 1

interval:
    swipe: 1
    pinch: 1